...
AsynChord aChord = ...
MyCallback callback = new MyCallback(); 
...
String data = "Just an Example.";
StringKey myKey = new StringKey(data); 
aChord.remove(myKey, data, callback); 
//do other things
...
