...
Chord chord = ... 
// create or join 
...
String data = "Just an example."; 
StringKey myKey = new StringKey(data); 
try{
	chord.insert(myKey, data); 
} catch(ServiceException e){
	//handle exception
	...
}